[package]
name = "cross_widget"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
sauron-native = { path = "../../"}
wasm-bindgen = "0.2"
titik = { version = "0.2", optional = true }
log = "0.4"
console_log = { version = "0.1", optional = true }
pretty_env_logger = "0.3"
console_error_panic_hook = { version = "0.1"}


[features]
with-web = ["sauron-native/with-web", "console_log"]
with-titik = ["sauron-native/with-titik"]
with-gtk = ["sauron-native/with-gtk"]
with-nwg = ["sauron-native/with-nwg"]

